name: Setup

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      shell: bash
      with:
        node-version: 24
        registry-url: "https://registry.npmjs.org"

    - name: Install pnpm
      run: npm install -g pnpm
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash
