name: Install Lychee

runs:
  using: "composite"
  steps:
    - name: Install lychee
      run: curl -sSf https://sh.rustup.rs | sh -s -- -y && sudo apt install gcc pkg-config libc6-dev libssl-dev && cargo install lychee
      shell: bash
