name: CI

on:
  push:

jobs:
  build-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run unit tests
        run: pnpm test:unit

      - name: Install Playwright browsers
        run: pnpm --filter accented-devapp exec playwright install --with-deps

      - name: Run end-to-end tests
        run: pnpm test:e2e

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Publish (provisional)
        run: echo "Publish"
