name: CI

on:
  push:

jobs:
  build-test-publish:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Run unit tests
        run: pnpm test:unit

      - name: Install Playwright browsers
        run: pnpm --filter accented-devapp exec playwright install --with-deps

      - name: Run end-to-end tests
        id: test-e2e
        run: pnpm test:e2e

      - name: Archive end-to-end test results
        if: ${{ failure() && steps.test-e2e.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-results
          path: packages/devapp/test-results

      # https://pnpm.io/using-changesets
      - name: Setup npmrc
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/snapshot')
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Create release PR or publish
        if: github.ref == 'refs/heads/main'
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          # We're not using the default github token because actions generated by a workflow using a default token
          # can't generate other workflows:
          # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow#triggering-a-workflow-from-a-workflow
          # Using a personal access token is one of the recommended workarounds.
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Snapshot release
        if: startsWith(github.ref, 'refs/heads/snapshot')
        run: pnpm changeset version --snapshot && pnpm --filter accented publish --no-git-checks --tag snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
