name: CI

on:
  push:

jobs:
  build-test-publish:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      # - name: Run unit tests
      #   run: pnpm test:unit

      # - name: Install Playwright browsers
      #   run: pnpm --filter accented-devapp exec playwright install --with-deps

      # - name: Run end-to-end tests
      #   run: pnpm test:e2e

      # - name: Publish
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   run: pnpm publish-lib
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     NPM_CONFIG_PROVENANCE: true

      - name: Create Release Pull Request
        if: github.ref == 'refs/heads/dev'
        uses: changesets/action@v1
        with:
          publish: pnpm changeset-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
